/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface SquareComponent {
        "onSquareClick": any;
        "value": string;
    }
    interface TttComponent {
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLSquareComponentElement extends Components.SquareComponent, HTMLStencilElement {
    }
    var HTMLSquareComponentElement: {
        prototype: HTMLSquareComponentElement;
        new (): HTMLSquareComponentElement;
    };
    interface HTMLTttComponentElement extends Components.TttComponent, HTMLStencilElement {
    }
    var HTMLTttComponentElement: {
        prototype: HTMLTttComponentElement;
        new (): HTMLTttComponentElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "square-component": HTMLSquareComponentElement;
        "ttt-component": HTMLTttComponentElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface SquareComponent {
        "onSquareClick"?: any;
        "value"?: string;
    }
    interface TttComponent {
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "square-component": SquareComponent;
        "ttt-component": TttComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "square-component": LocalJSX.SquareComponent & JSXBase.HTMLAttributes<HTMLSquareComponentElement>;
            "ttt-component": LocalJSX.TttComponent & JSXBase.HTMLAttributes<HTMLTttComponentElement>;
        }
    }
}
